### PR TITLE
Make a warning like the one Discord has

### PR DESCRIPTION
**Pull request by Splatterxl**
### We don't want people losing their bot to unknown scammers, do we?

I've added a warning in the console (very similar to the one Discord has). I've also added a variable called `mynameisjeff` which can be changed to `0` to trigger the warning.

Overall, I think this is a small, but powerful thing to add to the project.

**Note**: VS Code automatically formatted the document.

### CODE REVIEW

**Review by SebOuellette — COMMENTED** [review]
This formatting does not meet our standard. They need that extra tab because they are within the html tags. Also your variable name mynameisjeff also doesn't meet our standard, since it doesn't explain what it does at all. The code is also just going to write all this contents to the console once, so there's no point of having it on an interval, with the variable in the first place. Your if statement is incredibly inefficient, cause you can just check if it's not equal to 1, then return, or put the other code in those brackets. Nothing about this code makes any sense, so sorry but we have to deny this PR

**Comment by SebOuellette** [comment]
We also don't want this on an interval cause that makes it so much worse to debug for us, and people who use livebot. Somebody who uses livebot will have made their own bot, they understand what they're doing

**Comment by Splatterxl** [comment]
As I understand, you are a "self-taught" programmer.

Maybe, since you are "self-taught", you could show some respect to other "self-taught" programmers.

Also, since you are the author of this repository, you can format, change and modify the code.

Also also, I'm not responsible for Visual Studio Code's formatting standards.

**Comment by Splatterxl** [comment]
You might be able to change `mynameisjeff` to `interval_var` or something you would like.

You might be able to delete the interval.

**Comment by Splatterxl** [comment]
Don't just make assumptions. Maybe, if I trusted you, I would show you my bot repositories. I would like to think you would understand that I am also a bot programmer.

**Comment by Splatterxl** [comment]
I am incredibly disappointed with the standard of this project, and have deleted my fork and blocked you.

**Comment by PhoenixOnARoof** [comment]
> I am incredibly disappointed with the standard of this project, and have deleted my fork and blocked you.

And I am disappointed that you would get upset over this.

**Comment by Splatterxl** [comment]
> > I am incredibly disappointed with the standard of this project, and have deleted my fork and blocked you.
> 
> And I am disappointed that you would get upset over this.

I am disappointed you are disappointed.

**Comment by Splatterxl** [comment]
@SebOuellette you commit (twice at most) a month.

@Splatterxl commits once a week.

**Comment by PhoenixOnARoof** [comment]
> @SebOuellette you commit (twice at most) a month.
> 
> @Splatterxl commits once a week.
> 
> @PhoenixOnARoof commits twice a year.

Your point is?

**Comment by Splatterxl** [comment]
> > @SebOuellette you commit (twice at most) a month.
> > @Splatterxl commits once a week.
> > @PhoenixOnARoof commits twice a year.
> 
> Your point is?

figure it out

**Comment by Splatterxl** [comment]
also @SebOuellette check out [the GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines)

**Comment by dcrime** [comment]
I'll break it down for you
When we add stuff we make sure it's known what it does with the variable name for ease of reading, you can see that in any of the files

Visual studio code doesn't have to format on save, I don't have it format anything on save but on a default keybind `shift + alt + f`

You're not using `;` at the end of your functions and variables which is shown everywhere throughout the code unless we missed it (mostly me)

Your original frok didn't have a loop going every 10 seconds and it was fine but I at least let Sharky see the code first when he had time to check it out

This warning message could prevent others from listening when they have a problem and we tell them to paste something in like the infinite loading screen bug which is the most common problem

Yes, the project is boring so there aren't many commits done to it, we've talked about it and it's a hobby project, we don't get paid for it, we do it when we feel like it, it's not a responsibility to continue this.

There's no reason to make such a fuss about all of this, and if you thought that having an interval run every 10 seconds for something that is executed once then you're in the wrong because that's a waste of resources
A better way would be what discord actually did do and that's on opening the console which is way more optimized

**Comment by dcrime** [comment]
I have read the link you sent and we'll talk about the contributing.md file, thank you for the suggestion and if you plan on contributing again then please make it like you would in your bot rather than an experiment

**Pull request closed without merging**
