### PR TITLE
Reactions! and protip in member menu.

### PR DESCRIPTION
**Pull request by LukasDoesDev**
# Changelog

## 1
image of reactions
You can only react to what others have reacted.
I'll need to add a reaction selector but I don't know how.

## 2
And I also made a protip in the member menu.

image of member menu

## 3
And now the titlebar colors don't change when unfocused.
image of titlebar unfocused
By the way, I have multiple monitors, and `Win + Shift + S` lets me take images of multiple displays at the same time.

Edit:
image of discord console where I got banned
Thanks **official** discord console for telling me that.

## 4
🐛 Fixed issue #70 
image of fixed issue number seventy

and in the same commit, I fixed an XSS vulnerability 
image of fixed XSS vulnerability

### CODE REVIEW

**Comment by LukasDoesDev** [comment]
It's funny how you haven't said anyhting.

**Comment by LukasDoesDev** [comment]
You also fixed the XSS vulnerability because of me. I know you are feeling greedy and saying that you know everything. You banned me because I was making valid suggestions.

**Comment by SebOuellette** [comment]
Bruh

**Comment by SebOuellette** [comment]
If you want to make all these changes, you go ahead, that's why it's open source. I don't want to add all this to my project especially since you're needing to revert a lot of them, doesn't fill me with a ton of confidence.

**Pull request closed without merging**
