### PR TITLE
UI and .gitignore

### PR DESCRIPTION
**Pull request by LukasDoesDev**
- I added Github's Node.js gitignore from https://github.com/github/gitignore/blob/master/Node.gitignore.
- Made window title bold, uppercase, and made the letter spacing a bit smaller.
- Cleaned up some files but ended up reverting them.

### CODE REVIEW

**Comment by LukasDoesDev** [comment]
Why did you close this?

**Comment by SebOuellette** [comment]
1. We don't need the whole gitignore, we only have it set to what we need which makes it easier to see what we are doing
2. I do not want the variable names changed. 
3. I don't like the font change in the titlebar
4. I don't know exactly what you changed in most of these files cause you reverted everything.

**Comment by LukasDoesDev** [comment]
I reverted the variable name changing

**Comment by SebOuellette** [comment]
1/4

**Comment by LukasDoesDev** [comment]
Wait didn't I add the protip thing?

**Comment by LukasDoesDev** [comment]
Oh, I didn't commit it here.

**Comment by LukasDoesDev** [comment]
push*

**Comment by Splatterxl** [comment]
"We".

You banned the biggest contributor from the Discord Server, @SebOuellette.

**Comment by nearlySplat** [comment]
4. maybe you can check the files changed (as far as I know there's a button to look at that)

**Comment by SebOuellette** [comment]
As I said, I didn't want a lot of these changes.

**Pull request closed without merging**
