### PR TITLE
inline replies

### LINKED ISSUE #107: [SUGGESTION] The reply feature
This is a great tool. I've been wondering if adding replies was possible?

### PR DESCRIPTION
**Pull request by nearlySplat**
Added inline replies support.

This is hacky workaround, and Discord.js's master branch has official support for inline replies. I'm hesitant, however, to install discord.js@master since it has a *lot* of breaking changes.

Resolves #107

### CODE REVIEW

**Comment by nearlySplat** [comment]
If any issues arise from this, especially bugs, feel free to @ping me and let me know!

**Comment by nearlySplat** [comment]
(sorry for the mention, ping)

**Comment by maalos** [comment]
kinda sus, ngl

**Comment by nearlySplat** [comment]
LMFAO

**Comment by maalos** [comment]
so funny hahahaha

**Comment by NitroDisPro** [comment]
I see the reply to message option but it doesn't work?

**Comment by nearlySplat** [comment]
Sorry for the late response, but if you could supply the exact error (if any) that you're encountering, I would be more able to help you.

I'm not in a position to test it myself at the moment, so yeah.

**Comment by dcrime** [comment]
I'll test it in a bit, kinda getting a bit of motivation and if the code here looks good, I'll make a pr of my own branched off this that should fix some of the major obstacles that people face :P

**Comment by maalos** [comment]
> I'll test it in a bit, kinda getting a bit of motivation and if the code here looks good, I'll make a pr of my own branched off this that should fix some of the major obstacles that people face :P

bruh

**Comment by nearlySplat** [comment]
I've tracked down the issue. There's no UI acknowledgement for replied messages in the message list, and I've come to the conclusion that we need to either modify Discord.js internals or just download the master branch for replied messages to be fully supported.

-----

In the case we need to download the master branch, I'll have to do some huge bug fixes since a lot of the code base of Discord.js has changed even since v12.5.3.

**Comment by dcrime** [comment]
> I see the reply to message option but it doesn't work?

So I actually had to change it and planned on finding how to use replies but someone already had a solution for them
So I just ported that code over to LB and then adapted it to work, that's the only function as of now since it's not stylish and all (And since it was just to get it working, I didn't bother about switching channels canceling the whole reply)

**Comment by nearlySplat** [comment]
I'm going to close this since it's very inactive

**Pull request closed without merging**
