### PR TITLE
Create Start.bat

### PR DESCRIPTION
**Pull request by yanNotDev**
for lazy people who dont wanna open a cmd, just open the bat file and its ready to go (you can make a shortcut of it so its like an exe)

### CODE REVIEW

**Comment by dcrime** [comment]
It was considered but never added, Don't remember the reasoning, perhaps it's cause it can be ran on linux so to cause less confusion or less clutter?

**Comment by KifoPL** [comment]
1. it needs installing npm on the first run
2. not compatible with linux

**Comment by Dark42ed** [comment]
> 2. not compatible with linux

Then just add a `start.sh` along with it for the linux users?

**Comment by nearlySplat** [comment]
Why don't you actually open the terminal and type one line? It's not as if people are too lazy to use their keyboard and mouse...

**Comment by nearlySplat** [comment]
If there was a hugely complicated start script, I'd understand, but this is just preposterous.

**Comment by Dark42ed** [comment]
There's really no point in creating a start file unless it requires more than like 2 commands. If you want to make one yourself then go ahead.

**Review by nearlySplat — CHANGES_REQUESTED** [review]
Do not merge this, it is extremely unnecessary

**Comment by Oakchris1955** [comment]
> Do not merge this, it is extremely unnecessary

Indeed it is, but there might be someone who doesn't know how to write this on terminal

**Comment by Dark42ed** [comment]
> > Do not merge this, it is extremely unnecessary
> 
> 
> 
> Indeed it is, but there might be someone who doesn't know how to write this on terminal

If someone doesn't know how to write on the terminal, then they would use the executable. Also they have to `npm install` so you're kind of missing on that. And if they don't know how to write on the terminal, chances are they wouldn't have node installed.

**Comment by nearlySplat** [comment]
> > Do not merge this, it is extremely unnecessary
> 
> Indeed it is, but there might be someone who doesn't know how to write this on terminal

If there are, then just tell them to press CTRL+R, then type `cmd /c npm install && npm test`.

**Comment by nearlySplat** [comment]
@AayanTDE The `executable` exists just for this.

**Comment by Kiffolisk** [comment]
me when i can't run "npm test"

**Pull request closed without merging**
